

# This file was *autogenerated* from the file find_field_size.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import sys

prime = int(sys.argv[_sage_const_1 ])
print(int(ceil(log(prime, _sage_const_2 ))))

