

# This file was *autogenerated* from the file find_alpha.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
PRIME = int(sys.argv[_sage_const_1 ])

for i in Primes():
  if gcd(i, PRIME-_sage_const_1 ) == _sage_const_1 :
    print(i)
    break

